<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integrador.Domain\Integrador.Domain.csproj" />
    <ProjectReference Include="..\Integrador.Infrastructure\Integrador.Infrastructure.csproj" />
    <ProjectReference Include="..\Integrador.Util\Integrador.Util.csproj" />
  </ItemGroup>

</Project>
